### ISSUE TITLE
FuelSDK?

### ISSUE THREAD

**Issue by phpguru** [davispeixoto/Laravel-5-Salesforce#1]
Can I use this extension to interact with ExactTarget via their [FuelSDK](https://code.exacttarget.com/apis-sdks/fuel-sdks/php/getting-started-with-the-php-sdk.html)?

**Comment by davispeixoto** [comment]
Hi Geoffrey,

I didn't see any impeditives using this combo once you make sure the data format used for both are normalized.

**Comment by davispeixoto** [comment]
As I didn't made this integration before, I will wait you to reply if got success to close this issue.

**Comment by davispeixoto** [comment]
Hi Geoffrey,

I'm closing this issue. Please reopen it if you got any further findings on the subject.
