### ISSUE TITLE
query() doesn't return all the fields 

### ISSUE THREAD

**Issue by bunlongheng** [davispeixoto/Laravel-5-Salesforce#10]
I try to use **query()**

`$records = Salesforce::query("SELECT Id, Name, Patient_Status_del__c, DOB__c, Patient_Sub_status_del__c FROM Patients__c");`

`dd($records);`

How comes, I got only 3 fields back ? 

```

    0 => {#198 ▼
      +"Id": "a005000000fGKmUAAW"
      +"DOB__c": "1971-03-09"
      +"Name": "PT-000140"
    }
    1 => {#199 ▼
      +"Id": "a005000000fG0wzAAC"
      +"DOB__c": "1961-05-29"
      +"Name": "PT-000139"
    }
    2 => {#200 ▼
      +"Id": "a005000000f0POeAAM"
      +"DOB__c": "1991-08-11"
      +"Name": "PT-000010"
    }


```

**Comment by davispeixoto** [comment]
There are a few possibilities: 
- are the values null at salesforce?
- are the values a representation for another objects?
- is your wsdl updated? did you cleared the php wsdl caches?

**Comment by davispeixoto** [comment]
@bunlongheng , any progress?

**Comment by davispeixoto** [comment]
Seems too abandoned... closing.

If needs reopen, just let me know.
