### ISSUE TITLE
Documentation - SALESFORCE_TOKEN is vague

### ISSUE THREAD

**Issue by robbiemoore** [davispeixoto/Laravel-5-Salesforce#11]
The documentation specifies that the auto-config requires these env variables.

SALESFORCE_USERNAME
SALESFORCE_PASSWORD
SALESFORCE_TOKEN

However I'm not sure what the SALESFORCE_TOKEN refers to, can anyone help out here/how do I find it? Thanks

**Comment by davispeixoto** [comment]
https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_concepts_security.htm
