### ISSUE TITLE
queryAll still only returning 500 records

### ISSUE THREAD

**Issue by chorton** [davispeixoto/Laravel-5-Salesforce#13]
I am performing Salesforce::queryAll('query here') and no matter what I do, I only get 500 records.  I would think that queryAll would return ALL the records?  I don't want to have to re-invent the wheel by writing an iterator to perform queryMore requests.

What's the trick to get this to work the way queryAll() is supposed to work?

**Comment by davispeixoto** [comment]
@chorton , the queryAll method is for retrieving even deleted objects (once Salesforce use soft deletes for all objects), and not to retrieve all records for a query bypassing their limits.

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_queryall.htm

**Comment by chorton** [comment]
Ah!!!!  I understand now.  Sorry about that.  Is there something built-in to this library that would make it easy to get all the records?  or am I just going to have to handle the check and execute a queryMore if needed myself?

**Comment by davispeixoto** [comment]
@chorton , this library is just a wrapper over the Salesforce SOAP api, and unfortunately does not implement any syntactic sugar, so you will need to implement an iterator using the queryMore.
