### ISSUE TITLE
INVALID_LOGIN: Invalid username, password, security token; or user locked out.

### ISSUE THREAD

**Issue by karlpatrickespiritu** [davispeixoto/Laravel-5-Salesforce#17]
I am certainly correct that my credentials are correct. I even tried logging in into salesforce successfully a few times using those credentials. Is there anything that I am missing? I followed the installation docs.

**Comment by karlpatrickespiritu** [comment]
#18

**Comment by karlpatrickespiritu** [comment]
The pull request solved my issue.

**Comment by davispeixoto** [comment]
@karlpatrickespiritu , thx for your collaboration.

**Comment by karlpatrickespiritu** [comment]
no problem @davispeixoto. nice plugin btw 👍
