### ISSUE TITLE
Support Laravel 5.3

### ISSUE THREAD

**Issue by adrianlaraperez88** [davispeixoto/Laravel-5-Salesforce#20]
This package support laravel 5.3

**Comment by aoikle** [comment]
Same here.  When I run composer require "davispeixoto/laravel5-salesforce" "~1.0", I get the following errors:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install davispeixoto/laravel5-salesforce 1.0.4
    - Conclusion: don't install davispeixoto/laravel5-salesforce 1.0.3
    - Conclusion: don't install davispeixoto/laravel5-salesforce 1.0.2
    - Conclusion: don't install davispeixoto/laravel5-salesforce 1.0.1
    - Conclusion: remove vlucas/phpdotenv v2.4.0
    - Installation request for davispeixoto/laravel5-salesforce ~1.0 -> satisfiable by davispeixoto/laravel5-salesforce[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].
    - Conclusion: don't install vlucas/phpdotenv v2.4.0
    - davispeixoto/laravel5-salesforce 1.0.0 requires vlucas/phpdotenv ~1.0 -> satisfiable by vlucas/phpdotenv[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, v1.0.8, v1.0.9, v1.1.0, v1.1.1].
    - Can only install one of: vlucas/phpdotenv[1.0.0, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[1.0.1, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[1.0.2, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[1.0.3, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[1.0.4, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[1.0.5, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[1.0.6, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[v1.0.8, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[v1.0.9, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[v1.1.0, v2.4.0].
    - Can only install one of: vlucas/phpdotenv[v1.1.1, v2.4.0].
    - Installation request for vlucas/phpdotenv (locked at v2.4.0) -> satisfiable by vlucas/phpdotenv[v2.4.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by davispeixoto** [comment]
Hi @adrianlaraperez88 and @aoikle , can anyone of you make a pull request in order to address this? I'm currently involved with a systems migration for the company I work for and have no able time to do this for the next couple of weeks.

**Comment by adrianlaraperez88** [comment]
Hi @aoikle, I already managed it to work but the truth is I do not know what configuration I have to do in the developer.salesforce, since he passed the 4 parameters and tells me wrong authentication

**Comment by davispeixoto** [comment]
@adrianlaraperez88 Did you created everything as needed at salesforce.com for accessing via SOAP API, including getting the WSDL file? Verified if the user you are trying to log in has the proper permissions? All these are in the salesforce side...

**Comment by adrianlaraperez88** [comment]
Hello @aoikle, this would be my first project and really download the wsl enterprise and I use the same user and pass to enter the developer salesforce and token.


R/.
Exception at ConstructorLOGIN_MUST_USE_SECURITY_TOKEN: Invalid username, password, security token; Or user locked out. Are you at a new location? When accessing Salesforce - either via a desktop client or the API - from outside your company's trusted networks, you must add a security token to your password to log in. To get your new security token, log in to Salesforce. From your personal settings, enter Reset My Security Token in the Quick Find box, then select Reset My Security Token.

**Comment by davispeixoto** [comment]
Note sure which this library version are you using, please confirm. Also, take a time for ensure your salesforce.com credentials and stuff.

**Comment by adrianlaraperez88** [comment]
This is the version of the package I am using
"Davispeixoto / laravel5-salesforce": "dev-master", and I can log into developer salesforce

**Comment by chorton** [comment]
Hello,

I am now getting the same error but things were working fine even yesterday.

**Comment by adrianlaraperez88** [comment]
So this is bad, lol, he recommends me. ???

**Comment by adrianlaraperez88** [comment]
lol, in this moment 15 min locked Exception at ConstructorINVALID_LOGIN: Invalid username, password, security token; or user locked out.

**Comment by chorton** [comment]
Anyone have any idea which Laravel 5.3 subversion introduced this issue?  I've been on 5.3 all along, so it has to be a specific sub-version that introduced this issue.

**Comment by chorton** [comment]
I just tested various versions of Laravel 5.3 and they all result in a "Exception at ConstructorINVALID_LOGIN: Invalid username, password, security token; or user locked out...." exception.

what is odd is I've been on 5.3 since I started my project and never had any issues until today.

**Comment by adrianlaraperez88** [comment]
I commented that I could only mount this package in Laravel 5.2.

**Comment by ic-ravi** [comment]
using package "davispeixoto/laravel5-salesforce" "~2.0", i noticed that login call in Salesforce.php is: "$this->sfh->login($user, $pass, $token);" . The login method only accepts 2 parameters.

Looking into "davispeixoto/laravel5-salesforce" "~1.0", the call is: "$this->sfh->login($user, $pass . $token);"

Changing the login method in 2.0 to: "$this->sfh->login($user, $pass . $token);" fixed the issue for me.

Using laravel 5.3.4

**Comment by adrianlaraperez88** [comment]
The same mode of logging is kept as is the documentation

**Comment by adrianlaraperez88** [comment]
I have no problem installing it in laravel 5.3 but I still have the error in the auth, if they have some test sanbox that lend me to see if it is mine, I will be grateful

**Comment by adrianlaraperez88** [comment]
Nice

**Comment by aoikle** [comment]
Well I was finally able to install the package.  I'm using Laravel 5.3.26.  I wish there was better documentation for this package.  When I use the following code example from the github ,

use Davispeixoto\Laravel5Salesforce\Salesforce;
// I also tried 
use Salesforce
// but that crashes without error.

public function testSalesForce() {
	try {
		echo print_r(Salesforce::describeLayout('Account'), true);
	} catch (Exception $e) {
		echo $e->getMessage();
		echo $e->getTraceAsString();
	}
}

I get this error: 
Call to undefined method Davispeixoto\Laravel5Salesforce\Salesforce::describeLayout()

**Comment by ic-ravi** [comment]
Got around that error by extending the facade:

use Davispeixoto\Laravel5Salesforce\SalesforceFacade as Salesforce;

**Comment by davispeixoto** [comment]
Finally I got some time to work on it.

The main issue is that you guys are installing the version 1.0 which is intended to be used with Laravel 5.1.

For Laravel 5.2 and 5.3, you need the version 2+ (currently 2.0.6). For login issues I've made a quick fix and published it.

For class not being found, the problem is with the setup (need to add the saleforce class on both providers and aliases).
