### ISSUE TITLE
Partner.wsdl methods not reading

### ISSUE THREAD

**Issue by ic-ravi** [davispeixoto/Laravel-5-Salesforce#21]
Call to undefined method Davispeixoto\Laravel5Salesforce\Salesforce::describeLayout()

I am trying to set it up on lumen framework v5.3.4 (l5sf version 2) but none of the partner.wsdl methods work. Also setup a laravel 5.2 application with the same version with the same issue.

I have the credentials and enterprise wsdl working on an older application with l5sf version ~1.0

Appreciate your feedback

**Comment by davispeixoto** [comment]
@ic-ravi , have you tried to clean up wsdl/soap caches??

**Comment by ic-ravi** [comment]
@davispeixoto , i managed to work around it by referencing the facade instead of the class. Now having the login token error mentioned in the other issue.
