### ISSUE TITLE
INVALID_TYPE: Must send a concrete entity type.

### ISSUE THREAD

**Issue by Lam784** [davispeixoto/Laravel-5-Salesforce#22]
Hey Davis, 

I am trying to create an opportunity in salesforce, and I am getting this error: 'INVALID_TYPE: Must send a concrete entity type.'.

I am not too familiar with the enterprise client, and I couldn't find a solution on Google, can you spot anything wrong with my code? Because the they querying works, but not the create();

Here is my code:
            $sfOpportunity = new \stdClass();
            $sfOpportunity->AccountId = $accountId;
            $sfOpportunity->Name = $oppName;
            $sfOpportunity->StageName = $stageName;
            $sfOpportunity->CloseDate = $closeDate;
            $sfOpportunity->Type = $type;
            $sfOpportunity->CampaignId = $campaignId;
            $sfOpportunity->OwnerId = $ownerId;

            $result = $this->create(array($sfOpportunity), "Opportunity");

**Comment by davispeixoto** [comment]
Hi @Lam784 . Are you using PHP 7+?

If yes, then here you can find an answer: https://github.com/developerforce/Force.com-Toolkit-for-PHP/pull/49

It is with the underlying works for runtime pointers when iterating over arrays.

https://github.com/developerforce/Force.com-Toolkit-for-PHP/pull/49

Check and reply, please.

**Comment by Lam784** [comment]
Yup, that fixed it, thanks!

**Comment by nicklee1990** [comment]
@davispeixoto just ran into this today. how do we actually resolve this error? from looking at the issue im not actually sure what to do?

**Comment by davispeixoto** [comment]
Check the installation. Probably you are missing to declare and configure
properly at setup file

**Comment by nicklee1990** [comment]
which installation? I've got the latest version of davispeixoto/laravel5-salesforce.

I think https://github.com/davispeixoto/Force.com-Toolkit-for-PHP need a new release to make the latest commits available? And this package would need a composer.json update `"davispeixoto/force-dot-com-toolkit-for-php": "1.0.*",` to `"davispeixoto/force-dot-com-toolkit-for-php": "~1.0.*",`

**Comment by nicklee1990** [comment]
I just tested ^^^ locally using forks of your libs and my suggestion works. it seems there was some commits to https://github.com/davispeixoto/Force.com-Toolkit-for-PHP which fixed this issue but they were not released. Once they are released, and the composer.json for this library is updated to pull in the new release (which I assume would be 1.1.0), it will work

**Comment by davispeixoto** [comment]
I will double check this by Tuesday only. But I was referring to laravel5
salesforce package installation. It does change across versions

**Comment by nicklee1990** [comment]
cool - thanks!. it looks like https://github.com/davispeixoto/Force.com-Toolkit-for-PHP/pull/2 fixed the issue but never got released btw

**Comment by davispeixoto** [comment]
Alright, thx for the quick update. Thus I can check on this tomorrow
morning. It almost 1 am here in Brazil and I would not like to wake up my
children

**Comment by nicklee1990** [comment]
haha no problem! hope you manage to get some sleep!

**Comment by davispeixoto** [comment]
Sorry for the delay, folks.

I've published the pull request #2.

**Comment by davispeixoto** [comment]
@nicklee1990 , please send me your personal email at @DavisPeixoto at twitter, plz.
