### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by nicklee1990** [davispeixoto/Laravel-5-Salesforce#23]
When attempting to login outside a configured Secure network, I'm getting a message saying invalid login, need to supply token. 

It looks to me like the #18 is the cause for this, as if I revert back to a concatenation of password and token as it was before, it works fine. Any ideas what could be the cause or if there's something I should of done prior to moving to the latest version?

I'm on Laravel 5.2 and 2.0.5 (but also tried with dev-master) of this library.

**Comment by nicklee1990** [comment]
also looking at the force-dot-com library, https://github.com/davispeixoto/Force.com-Toolkit-for-PHP/blob/master/src/Davispeixoto/ForceDotComToolkitForPhp/SforceBaseClient.php#L164 the login method only accepts 2 parameters, but we're calling it here with 3 (the token being the third)

**Comment by davispeixoto** [comment]
@nicklee1990 , just found the error and fixed it. Please update to version 2.0.6+ and confirm

**Comment by nicklee1990** [comment]
Thanks! I'll test this evening

**Comment by nicklee1990** [comment]
FYI I can confirm this is fixed
