### ISSUE TITLE
please update to work with laravel 5.4

### ISSUE THREAD

**Issue by adam-jones-net** [davispeixoto/Laravel-5-Salesforce#28]
I get constant package installation issues as soon as I add your code to the composer.json file, most relating to "Can only install one of: vlucas/phpdotenv" version issues.

**Comment by davispeixoto** [comment]
Thx for the notification, @arkid .

I will update it as soon as possible - still this week, probably.

If you are in a hurry, you can make a pull request with the fix, so i can review and merge it.

**Comment by nicklee1990** [comment]
@arkid I've just done a fresh installation of 5.4 and required the package and it installed fine. Looking at the 5.4 composer file it requires `"vlucas/phpdotenv": "~2.2"` which is the same for this lib. Can you post some of the console output? Could be a conflict of a different dependency

**Comment by DarrenChowles** [comment]
To confirm, does this package work with 5.4+?

**Comment by davispeixoto** [comment]
@AnubisTheory , have you take a look into @nicklee1990 reply?

Which version of package are you referring to? 1.x or 2.x?

**Comment by DarrenChowles** [comment]
The latest version, I'll likely need to integrate SF into a Laravel 5.4 project soon and checking if it will work, given arkid's issue above, although nicklee1990 seems to confirm it will.

**Comment by davispeixoto** [comment]
@AnubisTheory , please make a simple test. Clone your environment, and then install the latest version (2.0.6), and update us regarding this status.

Everything makes me believe it will (releases 2.X are meant to be compatible with Laravel 5.2+).

But if needed I can create a new major release (3.X) to be compatible with higher versions.

I'm waiting a reply from you.

**Comment by davispeixoto** [comment]
@AnubisTheory , I'm assuming this is working, as other users are reporting success and you haven't replied in months.

**Comment by DarrenChowles** [comment]
The client ended up not going with SF so I never tried it, thanks for following up either way.
