### ISSUE TITLE
Login NULL Error

### ISSUE THREAD

**Issue by hugohernandezfcc** [davispeixoto/Laravel-5-Salesforce#30]
I've follow all steps to install the package in Laravel 5.4 and when execute the first sample is shown the error: 

`Exception at ConstructorINVALID_LOGIN: Invalid username, password, security token; or user locked out.
/sys/vendor/davispeixoto/force-dot-com-toolkit-for-php/src/Davispeixoto/ForceDotComToolkitForPhp/SforceBaseClient.php(176): SoapClient->__call('login', Array)`

I believe that the information of config/salesforce.php isn't received correctly because my credentials are correct (I did more of one test with Data Loader).

**Comment by davispeixoto** [comment]
Hi @hugohernandezfcc ,

I'd like you to do a quick sanity check:
- username is correct?
- password is correct?
- api access token is correct?
- wsdl is correct?
- soap caches are clear?
- user has api access enabled?
- user is **not** blocked?
- the [instance](https://status.salesforce.com/status) you tried logging in was up?

**Comment by hugohernandezfcc** [comment]
I apologize for the delay but all points was checked and none was wrong.... I had to create the project again and put my credentials and wsdls again and run correct.

When I am more relaxed I will continue with the issue and will share my error in the creation.

Thanks for you help from México ;D.

**Comment by davispeixoto** [comment]
Alright, @hugohernandezfcc , I will close this issue, but you can add you comments as complement and reference for future users
