### ISSUE TITLE
 INVALID_SESSION_ID: Invalid Session ID found in SessionHeader

### ISSUE THREAD

**Issue by rshah-cimpress** [davispeixoto/Laravel-5-Salesforce#32]
Hi, 

I have made a listner using Salesforce Facade , after few hours it throws following error  

INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session. Session not found, missing session hash: Ye11sapfRyGJUr6vk2IDg+PkGz/wyKYoY8K0z3H2xdc=
This error usually occurs after a session expires or a user logs out.

I have forced clear resolved instances, before using the facade.

Also lock session settings is unchecked in Salseforce workspace.

Can you please help.

**Comment by davispeixoto** [comment]
Hello @rshah-cimpress . Actually I can't help in that case. This does not seems to be related to the library itself, but your application or your environment settings.

By default the libraries are designed to reconnect on each new instantiation, but your application or environment seems to be caching it, so I think you need to find where/why/how your application or env is  caching the created connection, and change it.

Check the SOAP package configuration and options, perhaps it is caching a successfull connection for longer than it should.

**Comment by rshah-cimpress** [comment]
Thanks @davispeixoto 

Yes it was issue with the instantiation, As the implementation is singleton in Serviceprovider the SoapClient object is cached, so once the session is timed out or logged out the SoapClient object has has to be re initiated
