### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by ruelrule05** [davispeixoto/Laravel-5-Salesforce#34]
Is there a plan for a 5.8 support? I upgraded our project to laravel 5.8 and used this package but there's an error on the dependency. vlucas/phpdotenv

**Comment by davispeixoto** [comment]
@ruelrule05 , at the present moment I'm not able to provide support to this version by myself. It will take until the weekend, so I can provide the support needed.

**Comment by davispeixoto** [comment]
@ruelrule05 , I've published the updates for Laravel 5.8. This library version you should use now is 3.0.0+ for Laravel 5.8+ compatibility

**Comment by ruelrule05** [comment]
@davispeixoto thank you for the update. I will be upgrading my project now.
