### ISSUE TITLE
Add config flag for WSDL_CACHE for dev environments

### ISSUE THREAD

**Issue by hemorej** [davispeixoto/Laravel-5-Salesforce#35]
When working in dev, the WSDL might change often and rather than have to write `ini_set("soap.wsdl_cache_enabled", 0);` in PHP I would love to be able to set a config flag when instantiating the Salesforce object. If the `APP_ENV` is debug or local, then disable the cache

**Comment by davispeixoto** [comment]
@hemorej , I totally understand your request, but this can have undesired side effects when working with multiple WSDL integrations, thus I think it is better to still let this as a explicit decision on developers side, as they might be aware of the behavior
