### ISSUE TITLE
Laravel 6.2 Support

### ISSUE THREAD

**Issue by ruelrule05** [davispeixoto/Laravel-5-Salesforce#36]
Hello, will we be expecting a Laravel 6.2 support soon?

**Comment by hemorej** [comment]
@ruelrule05 you can fork this repo and remove the L5 dependency in composer.json. So far it's working for me, but I'm still testing our app after upgrade to L6 so I can't say yet that it won't break

**Comment by davispeixoto** [comment]
Feel free to move on with that, guys. I really won't have much time to focus on open source as much as I would like this year.
