### ISSUE TITLE
How to setTimeout() for query?

### ISSUE THREAD

**Issue by klukiyan** [davispeixoto/Laravel-5-Salesforce#38]
Hi,
A query that usually takes 2 seconds, sometimes goes beyong the default 10 seconds.
Is there any way to increase timeout?
Please help

Thank you

**Comment by davispeixoto** [comment]
Hi @klukiyan . I guess this can help => https://salesforce.stackexchange.com/questions/99075/my-soql-select-is-timedout-sometimes

AFAIK, there is no way to increase limits. But you can refactor to limit the rows amount per query, thus reducing the amount of time needed to scan and return.

**Comment by klukiyan** [comment]
Hi @davispeixoto 
It didn't help. 
The default api time-out is 10 seconds. Salesforce accepts `timeout` header parameter that can be up to 120 seconds.
I've seen examples with Java and C#. I've seen one with PHP. But it was plain php. I'm trying find a place where your package is merging with the toolkit to inject this command. It looks somehting like this;
```php
$sfdc->setTimeout( 2*60*1000);
```

Can you help me to find where I could fit it? Where is the raw `header` constructed?

Thank you. And thank you for a great package!

**Comment by davispeixoto** [comment]
@klukiyan , thx for the compliments about the package.

Can you provide me a link to the documentation you mentioned? I'd like all links php, java and c#...

**Comment by klukiyan** [comment]
@davispeixoto ,
I will try to find it in my browser history. I was googling for 3 hours yesterday before coming here with questions. It will take me some time to find those links that contained PHP codes samples.
Here are few that make remarks about 10 and 120 seconds for start:

- [https://developer.salesforce.com/forums/?id=906F00000009ABuIAM](https://developer.salesforce.com/forums/?id=906F00000009ABuIAM)

- [https://salesforce.stackexchange.com/questions/99977/read-timeout-error-while-making-an-api-inbound-call-to-salesforce](https://salesforce.stackexchange.com/questions/99977/read-timeout-error-while-making-an-api-inbound-call-to-salesforce)


The error that I'm getting is `Error Fetching Http Headers`.
The scheduled hourly job on web server will get it everyhour, until I try to execute some simpler query, and after that it sometimes start to work again. Usually the query takes 2.5 seconds and returns 400 rows.

I don't know how to optimize it further:

```sql
SELECT Credit_Note__r.Name, Credit_Note__r.Type__c, Credit_Note__r.Expected_credit_note_date__c, Credit_Note__r.Settlement_Type__c, Credit_Note__r.Budget_Status__c, Credit_Note__r.Status__c, Credit_Note__r.CreatedDate, Credit_Note__r.Completed_Date__c, Credit_Note__r.Posting_Date_SAP__c, Credit_Note__r.Invoice_Number__c, Credit_Note__r.Cancellation_Correction__c, Credit_Note__r.Modification_Cancellation_Remarks__c, Credit_Note__r.Reposting__c, Credit_Note__r.Order_Type__c, Credit_Note__r.SAP_ID_Credit_Note__c, Credit_Note__r.Account_SAP_SO__c, Credit_Note__r.Plant__c, Credit_Note__r.Storage_location__c, Credit_Note__r.VAT_exception__c, Credit_Note__r.Billing_Heading_Text__c, Credit_Note__r.Do_Not_Send_Credit_Note_to_Customer__c, Credit_Note__r.Customer_s_Invoice_Number__c, Credit_Note__r.Comments__c, Credit_Note__r.Credit_note_Payment_Term__r.Name, Amount__c, Billing_item_text__c, Condition_Type_I__c, Condition_Type_Picklist__c, CurrencyIsoCode, Financial_Material_Reporting__c, Name, Order_Reason_Code__c, Order_Type__c, Original_invoice_number__c, Price_Difference__c, Product_for_SAP_Batch_Upload__c, Quantity_Difference__c, Quantity__c, Rebate_Amount__c, Stock_Compensation__c, Credit_Note__r.Current_Approver__c,  Division__c 
    FROM Credit_Note_Products__c 
    WHERE (Credit_Note__r.LastModifiedDate >= YESTERDAY OR LastModifiedDate >= YESTERDAY) AND Modification_Age__c < 0.5
```

I'll come back with more precise links later

**Comment by davispeixoto** [comment]
I see a few problems around here...

First, please bear in mind that the library I allowed here is for the SOAP API, not to REST API (or any other ones... Salesforce have a lot of them actually, like, data api, bulk api, UI, visualization api, analytics api...). The current library is for SOAP API, and you sent references for the REST API.

Second, I'm not seeing you limited your query using explicit LIMIT clause. This can lead to full table scans, thus making a query to run longer and longer as your records amount increase.

With that said, I didn't see any way to change the time limit for expiration for a REQUEST/API CALL, only for the SESSION you open (which usually closes after 2 hours).

Now getting into your specific error, It feels like it is all about your php settings. It seems that your wsdl/soap client configuration is closing the sockets before getting a reply. You can try changing this on your side.

Follow a few references about it.

https://stackoverflow.com/questions/9403486/error-fetching-http-headers-in-soapclient

http://php.blogaboutwhatever.com/2011/11/error-fetching-http-headers/

https://stackoverflow.com/questions/4824799/soapfault-exception-http-error-fetching-http-headers

**Comment by davispeixoto** [comment]
I'm gonna close this issue as this is not specifically related to the package, but rather to implementation practices and/or server setup.

**Comment by klukiyan** [comment]
@davispeixoto Thank you very much.
I've increased the default socket timeout and will see if failure happens again. 
Thank you for your help

## Update  
It did help. The problem is indeed on Salesforce side. Instead of responding in usual 2 seconds, it took over a minute

![image](https://user-images.githubusercontent.com/27725051/80870319-f79d6000-8ca5-11ea-985e-98e023f4c387.png)

**Very big thanks to you!**

**Comment by davispeixoto** [comment]
thx for your feedback, @klukiyan
