### ISSUE TITLE
Multiple Salesforce environments

### ISSUE THREAD

**Issue by klukiyan** [davispeixoto/Laravel-5-Salesforce#40]
Hi,
Thank you for your great work. It works perfectly.

Now I wanted to also query some data from Sandbox environment and can't figure out how could I use multiple accounts/environments?

Is there any way to inject different credentials for certain queries anyhow?

Thank you very much

**Comment by davispeixoto** [comment]
@klukiyan , I'm not an official Salesforce partner nor support channel. However, back in the days I worked with Salesforce, we need to enable the Sandbox environment on Salesforce and get credentials as well as a new wsdl file specific for Sandbox environment. With this WSDL and credentials it was possible to operate over sandbox. Hope this helps.

**Comment by klukiyan** [comment]
> @klukiyan , I'm not an official Salesforce partner nor support channel. However, back in the days I worked with Salesforce, we need to enable the Sandbox environment on Salesforce and get credentials as well as a new wsdl file specific for Sandbox environment. With this WSDL and credentials it was possible to operate over sandbox. Hope this helps.

Hi @davispeixoto ,
I have the Sandbox environment credentials and WSDL. 
I'm asking how to use them with your module. 
It accepts the Credentials and WSDL via config file. 
How could I make it use 2 sets of credentials?!

Thank you

**Comment by davispeixoto** [comment]
@klukiyan , this library wasn't designed with such case in mind, so I think this is not possible out of the box.

However, you can use the salesforce base library, the Salesforce (that you can find at https://github.com/davispeixoto/Force.com-Toolkit-for-PHP), to make a solution out of the box, and still count with a pretty good library. The current one for Laravel is just a Laravel-flavor package for that library
