### ISSUE TITLE
Object Mapping not working properly

### ISSUE THREAD

**Issue by saschaarthur** [davispeixoto/Laravel-5-Salesforce#5]
moved to https://github.com/deniamnet/force-dot-com-toolkit-for-php/issues/1 , please close

**Comment by davispeixoto** [comment]
@saschaarthur , have you solved it already or not?

**Comment by saschaarthur** [comment]
hey, its not solved yet
Am 08.06.2016 2:26 nachm. schrieb "Davis Peixoto" <notifications@github.com

**Comment by davispeixoto** [comment]
Have you changed your wsdl recently?

There are two points for consider when you do this. First is to update your wsdl file (you grab it from salesforce). You need to update and deploy this file before running the query, whenever you create or change any object (even a field type).

If you have done this, your wsdl may be cached. [By default PHP SOAP library come with WSDL cache enabled](http://php.net/manual/en/soap.configuration.php#ini.soap.wsdl-cache-enabled). So you may need to clear it to successfully use your changes.

@saschaarthur Can you check the points mentioned above and update this issue, please?

**Comment by saschaarthur** [comment]
thanks, wsdl caching was the issue.

**Comment by davispeixoto** [comment]
yw, @saschaarthur
