### ISSUE TITLE
SalesForce TLS error

### ISSUE THREAD

**Issue by jokerxvier** [davispeixoto/Laravel-5-Salesforce#6]
Hi Guys,

I would like to ask on how to fixed the error below. 

Exception at ConstructorUNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.

I can't connect to there api because of this error.

**Comment by davispeixoto** [comment]
@jokerxvier , PHP SoapClient uses cURL under the hood, which uses OpenSSL for secure connections, and perhaps this issue has relation with supported/installed protocols for your machine, not being a specific Salesforce issue, but an installation/environment issue.

Consider verifying OpenSSL and cURL versions installed at your server and perhaps upgrade them.
