### ISSUE TITLE
What is wsdl ? 

### ISSUE THREAD

**Issue by bunlongheng** [davispeixoto/Laravel-5-Salesforce#7]
According to your packages, you told to set 

```
 'wsdl' => storage_path('app/' . env('SALESFORCE_WSDL', 'wsdl/enterprise.wsdl.xml')),
```

What is mine should look like ? How do I know it ?

I keep getting

<img width="951" alt="screen shot 2016-07-16 at 3 58 16 pm" src="https://cloud.githubusercontent.com/assets/11523064/16896861/27d36c42-4b6e-11e6-9031-f1263532434e.png">

**Comment by davispeixoto** [comment]
You can find it following these instructions:

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_quickstart_steps_generate_wsdl.htm

**Comment by bunlongheng** [comment]
Got it thank-you !
